server:
  port: 7001
eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主
    preferIpAddress: true #访问路径可以显示IP地址

zuul:
  routes:
    povider-product:
      path: /product/**
      serviceId:  microservice-product
      stripPrefix: false

